package ServicesProjectMPR;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

import ProjectMPR.Student;
import ProjectMPR.Studies;
import ProjectMPR.Subiect;

public class StudiesDBMenager {
	
	private Connection conn;

	private Statement createTable;
	
	private PreparedStatement addStudiesStmt;
	
	private PreparedStatement getStudiesStmt;
	
	public StudiesDBMenager(){
	
	try {
		conn = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb");		
		createTable = conn.createStatement();
		ResultSet rs=conn.getMetaData().getTables(null, null, null, null);
		boolean StudiesTableExists=false;
		while(rs.next())
		{
			if("Studies".equalsIgnoreCase(rs.getString("Table_Name")))
			{
				StudiesTableExists=true;
				break;
			}
		}
		if(!StudiesTableExists)
		{
		createTable.executeUpdate("" +
		"CREATE TABLE Studies(" +
		"id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
		"name varchar(20)," +
		"" +
		")");
		}
		
		addStudiesStmt=conn.prepareStatement("" +
				"INSERT INTO Studies (name) VALUES (?)" +
				"");

		getStudiesStmt=conn.prepareStatement("" +
				"SELECT * FROM Studies" +
				"");
		
	} catch (SQLException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	}
	public void addStudies(Studies s){
	try {
	addStudiesStmt.setString(1, s.getName());

	addStudiesStmt.executeUpdate();

	} catch (SQLException e) {

	e.printStackTrace();
	}

	}

	public List<Studies> getAllStudies()
	{
	List<Studies> studies=new ArrayList<Studies>();

	try {
	ResultSet rs= getStudiesStmt.executeQuery();

	while(rs.next())
	{
	studies.add(new Studies(rs.getString("name"),new ArrayList<Student>(),new ArrayList<Subiect>()));
	}

	} catch (SQLException e) {
	// TODO Auto-generated catch block
	e.printStackTrace();
	}

	return studies;
	}

}