package ServicesProjectMPR;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import ProjectMPR.Subiect;

public class SubiectDBMenager {

	private Connection conn;
	private Statement createTable;
	private PreparedStatement addSubiectStmt;
	private PreparedStatement getSubiectStmt;
	private PreparedStatement deleteAllSubiectStmt;
	private PreparedStatement findSubiectByNameStmt;
	private PreparedStatement findSubiectBySubiect_nrStmt;
	private PreparedStatement deleteSubiectStmt;	
	
	public SubiectDBMenager(){
		
		try {
			conn = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb");		
			createTable = conn.createStatement();
			ResultSet rs=conn.getMetaData().getTables(null, null, null, null);
			boolean SubiectTableExists=false;
			while(rs.next())
			{
				if("Subiect".equalsIgnoreCase(rs.getString("Table_Name")))
				{
					SubiectTableExists=true;
					break;
				}
			}
			if(!SubiectTableExists)
			{
			createTable.executeUpdate("" +
			"CREATE TABLE Subiect(" +
			"id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
			"subiect_nr Integer,name varchar(100)"+
			""  +
			")");
			}
			
			addSubiectStmt = conn.prepareStatement("INSERT INTO Subiect (subiect_nr, name) VALUES (?, ?)");

			getSubiectStmt = conn.prepareStatement("SELECT * FROM Subiect");

			deleteAllSubiectStmt = conn.prepareStatement("DELETE FROM Subiect");
			
			findSubiectByNameStmt = conn.prepareStatement("SELECT * FROM Subiect WHERE name= ?");
			
			findSubiectBySubiect_nrStmt = conn.prepareStatement("SELECT * FROM Subiect WHERE subiect_nr= ?");
			
			deleteSubiectStmt = conn.prepareStatement("DELETE FROM Subiect WHERE ID = ?");
			
			
		} catch (SQLException e) {
			
			e.printStackTrace();
		}
		}
	

	public void addDBSubiect(Subiect s1) {
		try 
		{
				addSubiectStmt.setInt(1, s1.getID_subiect());
				addSubiectStmt.setString(2, s1.getName());
				addSubiectStmt.executeUpdate();
		} 
		catch (SQLException e) 
		{

			e.printStackTrace();
		}
		
	}
	
	public List<Subiect> getAllSubiect(){
		List<Subiect> subiects=new ArrayList<Subiect>();

			try {
				ResultSet rs= getSubiectStmt.executeQuery();

				while(rs.next())
				{
				subiects.add(new Subiect(rs.getInt("subiect_nr"),rs.getString("name")));
				}

			} catch (SQLException e) {
		
			e.printStackTrace();
		}

		return subiects;
		}

		public void deleteAllSubiect() {
			try {
				deleteAllSubiectStmt.executeUpdate();
			} 
			catch (SQLException e) 
			{
				e.printStackTrace();
			}
		}
		
		public List<Integer> findSubiectByName(String name) {
			try {
				List<Integer> result = new ArrayList<Integer>();
				findSubiectByNameStmt.setString(1, name);
				ResultSet rs = findSubiectByNameStmt.executeQuery();
				while (rs.next())
					result.add(rs.getInt("ID"));
				return result;
			} catch (SQLException e) {
				e.printStackTrace();
			}
			return null;
		}
		
		public List<Integer> findSubiectBySubiect_nr(int subiect_nr) {
			try {
				List<Integer> result = new ArrayList<Integer>();
				findSubiectBySubiect_nrStmt.setInt(1, subiect_nr);
				ResultSet rs = findSubiectBySubiect_nrStmt.executeQuery();
				while (rs.next())
					result.add(rs.getInt("ID"));
				return result;
			} catch (SQLException e) {
				e.printStackTrace();
			}
			return null;
		}
		
		public void deleteSubiect(List<Integer> students) {
			try {
				for (Integer id : students) {
					deleteSubiectStmt.setInt(1, id);
					deleteSubiectStmt.executeUpdate();
				}
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
}
